---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-aeae6438-2933-4141-b915-d801fa3f7b10-name-omni
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Ti
  csi:
    driver: csi-rook-ceph.cephfs.csi.ceph.com
    nodeStageSecretRef:
      name: rook-csi-cephfs-user
      namespace: csi-rook-ceph
    volumeAttributes:
      clusterID: csi-rook-ceph
      fsName: ceph-filesystem
      pool: ceph-filesystem-data0
      rootPath: /volumes/csi/csi-vol-6144626c-736b-4fec-8a72-a536673909d4/9aa58fb5-4ea2-4e7e-b5c6-153adbdc8f89/omniverse
      staticVolume: "true"
      storage.kubernetes.io/csiProvisionerIdentity: 1685305850817-8081-csi-rook-ceph.cephfs.csi.ceph.com
      subvolumeName: csi-vol-6144626c-736b-4fec-8a72-a536673909d4
      subvolumePath: /volumes/csi/csi-vol-6144626c-736b-4fec-8a72-a536673909d4/9aa58fb5-4ea2-4e7e-b5c6-153adbdc8f89
    volumeHandle: 0001-000d-csi-rook-ceph-0000000000000001-6144626c-736b-4fec-8a72-a536673909d4-name-omni
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ceph-filesystem
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omniverse
  namespace: name-twin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  storageClassName: ceph-filesystem
  volumeMode: Filesystem
  volumeName: pvc-aeae6438-2933-4141-b915-d801fa3f7b10-name-omni
