---
# Default values for cdl-dataset.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

clusterName: ops.openark
nameOverride: ""
fullnameOverride: ""

claim:
  # whether to enable connected data lake's auto-select feature
  enabled: true

  affinity:
    placementAffinity:
      preferred: []
      required: []
    replacementAffinity:
      preferred: []
      required: []

  allowReplacement: true

  # binding policy presets
  # options: ["Balanced", "LowestCopy", "LowestLatency"]
  bindingPolicy: LowestCopy

# options: ["Retain", "Delete"]
deletionPolicy: Delete

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  requests:
    storage: 1Ti

static:
  sourceBindingName: null
  sourceStorageName: null
  targetStorageName: null
  syncPolicy:
    # options: ["Always", "OnCreate", "Never"]
    pull: Never
    # options: ["Always", "OnDelete", "Never"]
    push: Never
