---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: huggingface-hub-cache
  namespace: api
  labels:
    base: huggingface-hub
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: ceph-filesystem
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: huggingface-hub
#   namespace: api
#   labels:
#     app: text-generation
# stringData:
#   # TODO(user): change your own token!
#   # HELP: Go to https://huggingface.co/settings/tokens
#   HUGGING_FACE_HUB_TOKEN: "TODO"
